server:
  type: simple
  applicationContextPath: /

  connector:
    type: http
    port: 8080


swagger:
  resourcePackage: com.opingoo.services


database:
  driverClass: com.mysql.jdbc.Driver
  user: op-session-mgr
  password: opingoo_123

    # the JDBC URL
  url: jdbc:mysql://127.0.0.1:3306/opingooDB?autoReconnect=true

    # any properties specific to your JDBC driver:
  properties:
      charSet: UTF-8

    # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 30s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # The initial size of the connection pool.
  # initialSize must be between minSize and maxSize ( both inclusive )
  initialSize: 10

  # the minimum number of connections to keep open
  minSize: 10

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 30s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute


  # Remove abandoned connections if they exceed the removeAbandonedTimeout. If set to true a connection is considered abandoned and eligible for removal if it has been in use longer than the removeAbandonedTimeout and the condition for abandonWhenPercentageFull is met.
  #removeAbandoned: true

  checkConnectionOnConnect: true
  checkConnectionOnReturn: true
  checkConnectionOnBorrow: true

  #If true, logs stack traces of abandoned connections.
  logAbandonedConnections: true

  #If true, logs errors when connections fail validation.
  logValidationErrors: true

logging:

  level: INFO

  appenders:
    - type: file

      currentLogFilename: /home/pydev/log/opingoo.log #/home/ubuntu/log/opingoo.log
      archivedLogFilenamePattern: /home/pydev/log/opingoo-%d.log.gz
      archivedFileCount: 50
      threshold: ALL
      archive: true
      timeZone: UTC

    - type: console